Set ReleaseTag More Accurately
Signed-off-by: Sam Elliott <selliott@lowrisc.org>

diff --git a/_build-deps.yml b/_build-deps.yml
--- a/_build-deps.yml
+++ b/_build-deps.yml
@@ -13,3 +13,35 @@ steps:
 - bash: |
     ./install-crosstool-ng.sh
   displayName: 'Build and install crosstool-ng'
+
+- bash: |
+    set -e
+    git fetch --tags
+
+    # git-describe --always almost does what we want, but we need to connect the
+    # ReleaseTag variable contents to how this build was triggered, which we
+    # will find out using `Build.SourceBranch` (a pipeline varaible).
+    #
+    # Importantly, a few things are going on here:
+    # - If we were triggered by a tag, we need to set ReleaseTag to exactly the
+    #   tag name, so that the artifacts are named correctly. If we cannot do
+    #   this, the build needs to fail rather than uploading artifacts to some
+    #   other random tag.
+    # - If we were triggered by a branch build, we need to be more careful, as
+    #   tagged commits are also pushed to branches. Branch builds explicitly use
+    #   the longer format so that if the built commit matches a tag, the
+    #   ReleaseTag is not a tag name.
+    #
+    # This is partly caused by azure not always pulling down tags when checking
+    # out a repo, so we fetch tags again, above, just to make sure we have all
+    # current tags.
+    if [[ "$(Build.SourceBranch)" == refs/tags/* ]]; then
+      # Tag Build: Always use '<TAG>' format; Error if tag not found.
+      tag_name="$(git describe --exact-match)"
+    else
+      # Branch Build: Always use '<TAG>-<N>-<SHA>' format.
+      tag_name="$(git describe --long)"
+    fi
+
+    echo "##vso[task.setvariable variable=ReleaseTag]${tag_name}"
+  displayName: 'Set ReleaseTag'
